### ISSUE TITLE
Procuring entity instead of Organization Reference

### ISSUE THREAD

**Issue by yolile** [timgdavies/OCDS-mapping-sheet#3]
@Bjwebb When I use the generate.py for generate the mapping template, the resultant
file contains this rows:
tender tender/tenderers Tenderers 
tender tender/tenderers **Procuring entity**

Procuring entity instead of Organization Reference
And the same error is also present in award/suppliers 
When I erase this lines:
`if hasattr(obj[field], '__reference__'):`
 `obj[field].update(obj[field].__reference__)`

The mentioned fields are filled in good, but the rest of the object fields names are empty.

**Comment by Bjwebb** [comment]
This should be fixed now.
