### ISSUE TITLE
Missing objects descriptions

### ISSUE THREAD

**Issue by yolile** [timgdavies/OCDS-mapping-sheet#7]
The objects: Milestone, Value, Period, Classification and Identifier don't have the property "description" in the generated sheet.

**Comment by jpmckinney** [comment]
@yolile Do you have a fix for this issue? (re: https://crm.open-contracting.org/issues/2780)

**Comment by yolile** [comment]
I made a hard-core solution and pushed it here: https://github.com/open-contracting/mapping-sheet-generator/tree/organizations-titles

**Comment by jpmckinney** [comment]
I wonder if this is related to https://github.com/open-contracting/standard/issues/603

To see changes: https://github.com/open-contracting/mapping-sheet-generator/compare/organizations-titles

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/ocdskit/issues/25
